version: '3.8'

services:
  renogy-data-capture:
    # build:
    #   context: .
    # container_name: renogy-data-capture
    image: 192.168.1.141:5000/renogy-data-capture:1.1
    devices:
      # - /dev/serial1:/dev/serial1
      - /dev/hci0:/dev/hci0
    network_mode: host
    privileged: true
    volumes:
      - /run/dbus:/run/dbus:ro
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /var/lib/bluetooth:/var/lib/bluetooth
      - /etc/bluetooth:/etc/bluetooth
    environment:
      - USE_DOCKER_CONFIG=true
      # Device config
      - DEVICE_ADAPTER=hci0
      - DEVICE_MAC_ADDRESS=4C:E1:74:57:87:85
      - DEVICE_ALIAS=RTMShunt300
      - DEVICE_TYPE=RNG_SHNT
      - DEVICE_ID=255
      # RNG_CTRL => Charge Controller (Rover/Wanderer/Adventurer)
      # RNG_CTRL_HIST => Charge Controller historical data
      # RNG_BATT => Smart Battery
      # RNG_INVT => Inverter
      # RNG_SHNT => Smart Shunt

      # Data config
      - DATA_POLLING_ENABLED=false
      - DATA_POLL_INTERVAL=10
      - DATA_RATE_LIMIT_ENABLED=true
      - DATA_RATE_INTERVAL=10
      - DATA_TEMP_UNIT=F
      # fields to log (comma separated), leave empty for all fields
      - DATA_FIELDS=

      # Remote logging config
      - REMOTE_LOG_ENABLED=false
      - REMOTE_URL=https://example.com/post_endpoint
      - REMOTE_AUTH_HEADER=auth_header

      # MQTT config
      - MQTT_ENABLED=true
      - MQTT_CLIENT_ID=renogy-bt-smrt-shnt
      - MQTT_SERVER=192.168.1.227
      - MQTT_PORT=1883
      - MQTT_PUBLISH_TOPIC=renogy-ble/solar/shunt/state
      - MQTT_USER=mqtt_user
      - MQTT_PASSWORD=***********

      # PVOutput config
      - PVOUT_ENABLED=false
      - PVOUT_APIKEY=
      - PVOUT_SYSID=
    # Optional: If you want to pass a file with environment variables
    # env_file:
    #   - ./env_file.env
    #     networks:
    #       - bridge-network
